title: Introduction to Git
author: Akshay Borse
email: akshayborse@github.com
description: > In this blog I am going to explain Git concepts, features and how to use it

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  akshayborse

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
